- hosts: ipython-spark
  pre_tasks:
    - name: install apt packages
      apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
      sudo: True
      with_items:
        - python-pip
        - python-virtualenv
        - python-psycopg2
        - python-apt
        - unzip
        - tar
  roles:
     - { role: ansiblebit.oracle-java,
         oracle_java_set_as_default: yes,
         sudo: yes }
     - { role: azavea.ansible-spark,
         spark_version: "2.0.0-bin-hadoop2.7",
         spark_mirror: "http://www.us.apache.org/dist/spark/spark-2.0.0/",
         sudo: yes
       }
     - { role: anaconda, 
         python_version: 'python3',
         sudo: yes
       }
