- hosts: ipython-spark 
  gather_facts: False 
  sudo: True
  tasks: 
    - name: apt-get update 
      raw: apt-get update -qq 
    - name: Install python 2.7 
      raw: apt-get install -qq python2.7 
    - name: add hostname to /etc/hosts
      lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 localhost ubuntu-xenial' owner=root group=root mode=0644
    - name: install virtualbox guest utils 
      raw: apt-get --no-install-recommends install virtualbox-guest-utils


